# Generated by Django 6.0.3 on 2026-03-24 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('answer_a', models.CharField(max_length=255)),
                ('answer_b', models.CharField(max_length=255)),
                ('answer_c', models.CharField(max_length=255)),
                ('answer_d', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/')),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
            ],
        ),
    ]
