# Generated by Django 6.0.3 on 2026-03-24 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jatek', '0003_quiz_useranswer'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='useranswer',
            unique_together={('quiz', 'question')},
        ),
    ]
